### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by tkiefhaber** [rmtuckerphx/angular2-chromecast-receiver-starterkit#1]
Hey there!
Thanks for putting this together!  I'm trying to get this up and running locally and was able to get everything running except when it comes to getting to actually casting anything.

When I boot up the server here is what I see in the logs:
```
[1] 16.11.10 21:34:38 304 GET /app/screens/splash/splash.component.html
[1] 16.11.10 21:34:38 304 GET /images/logo.svg
[0] app/services/cast-receiver-manager/cast-receiver-manager.service.ts(14,5): error TS2304: Cannot find name 'cast'.
[0] app/services/cast-receiver-manager/cast-receiver-manager.service.ts(14,40): error TS2304: Cannot find name 'cast'.
[0] app/services/cast-receiver-manager/cast-receiver-manager.service.ts(16,20): error TS2304: Cannot find name 'cast'.
[0] app/services/cast-receiver-manager/cast-receiver-manager.service.ts(30,70): error TS2304: Cannot find name 'cast'.
[0] 9:34:39 PM - Compilation complete. Watching for file changes.
[1] [BS] File changed: app/services/cast-receiver-manager/cast-receiver-manager.service.js
```

The app launches and goes straight to the splash screen as expected.

Once I switch to the sender.html things are looking OK
<img width="869" alt="screen shot 2016-11-10 at 9 38 55 pm" src="https://cloud.githubusercontent.com/assets/1302793/20202609/69b4b6b2-a78e-11e6-9a52-0b01dd4954ff.png">

I select `Home Page` and a dialog pops up
<img width="965" alt="screen shot 2016-11-10 at 10 20 00 pm" src="https://cloud.githubusercontent.com/assets/1302793/20203272/f20422be-a793-11e6-9d8e-f5dc84e4aeb1.png">

The chromecast screen goes black on my TV for about 30 seconds and then goes to the screensaver.

If I click on another button, then I get a session error.
<img width="903" alt="screen shot 2016-11-10 at 9 40 16 pm" src="https://cloud.githubusercontent.com/assets/1302793/20202659/b6031374-a78e-11e6-9bd8-98d1cc9c2f2f.png">

Any ideas as to what might be going on?
The chromecast screen goes black like it's trying to do something, and the URL I have saved in my application in the console is the external.
I've tried all these pages locally and they work fine.  I've also used a chrom extension to cast a tab up to the thing to make sure that works and it does just fine.

Would love any help you have to offer.
Thanks!
Tom

**Comment by tkiefhaber** [comment]
Well, after turning things on and off a bunch of times, everything works....

Hooray computers!
Thanks again for putting this out there; it's going to be very helpful for me.

**Comment by rmtuckerphx** [comment]
Glad you got it working.

Looks to be an issue with the cast object not being found. The file, index.html, has a script tag for src="//www.gstatic.com/cast/sdk/libs/receiver/2.0.0/cast_receiver.js" and then the cast-receiver-manager.service.ts expects the cast object to be there.

Try debugging the receiver remotely and see if that reveals anything.
